name: var_sim
channels:
  - bioconda
  - anaconda
  - defaults
dependencies:
  - mysql-python=1.2.5
  - mysqlclient=1.3.10
  - biopython=1.72
  - numpy=1.15.3
  - pip=10.0.1
  - python=2.7.15
  - readline=7.0
  - setuptools=40.4.3
  - sqlalchemy=1.2.13
  - sqlite=3.25.2
  - pip:
    - autopep8==1.4.2
    - cython==0.29
    - gud==0.0.1
    - interval-binning==1.0.0
    - pbd==0.9
    - pylint==1.9.3

