name: var_sim
channels:
  - bioconda
  - anaconda
  - defaults
dependencies:
  - mysqlclient
  - mysql-connector-python 
  - biopython
  - numpy
  - pip
  - python=3.7
  - setuptools
  - sqlalchemy
  - zlib
  - pip:
    - autopep8
    - configparser
    - cython
    - datetime
    - interval-binning
    - lxml
    - pylint
    - sqlalchemy-utils
    - SQLAlchemy-FullText-Search

