name: GeneBreaker
channels:
  - bioconda
  - anaconda
  - defaults
dependencies:
  - biopython
  - numpy
  - pip
  - python=3.7
  - setuptools
  - sqlalchemy
  - zlib
  - pip:
    - autopep8
    - configparser
    - cython
    - datetime
    - lxml
    - pylint

