# This file created by conda-build 3.18.9
# ------------------------------------------------

package:
    name: curl
    version: 7.65.3
source:
    sha256: 0a855e83be482d7bc9ea00e05bdb1551a44966076762f9650959179c89fce509
    url: http://curl.haxx.se/download/curl-7.65.3.tar.bz2
build:
    noarch: false
    number: '0'
    string: hbc83047_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_8
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_8
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2019.5.15 1
        - krb5 1.16.1 h173b8e3_7
        - libcurl 7.65.3 h20c2e04_0
        - libedit 3.1.20181209 hc058e9b_0
        - libgcc-ng 9.1.0 hdf63c60_0
        - libssh2 1.8.2 h1ba5d50_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 he6710b0_1
        - openssl 1.1.1c h7b6447c_1
        - tk 8.6.8 hbc83047_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - krb5 >=1.16.1,<1.17.0a0
        - libcurl 7.65.3 h20c2e04_0
        - libgcc-ng >=7.3.0
        - libssh2 >=1.8.2,<2.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - curl --help
        - curl https://raw.githubusercontent.com/conda-forge/curl-feedstock/master/LICENSE
about:
    description: 'Curl is an open source command line tool and library for transferring
        data

        with URL syntax. It is used in command lines or scripts to transfer data.

        '
    dev_url: https://github.com/curl/curl
    doc_source_url: https://github.com/curl/curl/tree/master/docs
    doc_url: https://curl.haxx.se/docs/
    home: http://curl.haxx.se/
    license: MIT/X derivate (http://curl.haxx.se/docs/copyright.html)
    license_family: MIT
    license_file: COPYING
    summary: tool and library for transferring data with URL syntax
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - mingwandroid
        - msarahan
        - ocefpaf
