import unittest
from simulator.gene import Gene

class GeneCreation(unittest.TestCase):
    def setUp(self):
        chr=20
        start=0
        stop=8902        
        elements = [("exon", 0, 96),("exon", 8333, 8902),("intron",97,8332)]
        seq="""ATTCCTCAGGACACAGAGCTTCCTCTCTCCCAGGAGCCATGAATATCCTGATGCTGACCTTCATTATCTG
        TGGGTTGCTAACTCGGGTGACCAAAGGTAATGGAACCCTATAAAGCAGAGATGATGACTAGGATGAGTTG
        TTGCCCTTGGGCTCCCCTGGTATCATGATGGGAAGAGAGGGAATCTGCAGGAAAAATCTGGGCCAACAAA
        GAGCAGCAGAATGCTCTTATTTTGGCAGCTCCATGCCCCTAGTCTCTGAGAATCTTTCTGTTAGGGGCAT
        CTAGCAAGCTGGGATGTCCTCTGAGGCATTTCTCCAAAGACAAGAATTTCCTTAATGCTCTGAGCCACCC
        TATCTGTCTCTCTACATAACTATCCAATGTTAGTTCAGCCTCACTTCACTTCCATTTCGATTATTCTGTT
        GTATCTATTTCATTGTTGTGTCCTATTAGTTCTCCTACCATCTTGAATTCTTCTTTGCCCGGAGGGTACC
        TTCAGAGGGAGGCCCTCACTTTCATGTTCTTAGATATGGTGAACAAGTCCATTGACAGTTTGTAGATTCT
        GTAGCACTATCATATGGAAGAGACAATATATATGTTTGGGGTAGAAGTGGAAATAAGTGGAGTGAAGACA
        GGATAGACAGACTAGTGACCAATGGGGAGCTTCTAATTTTAGATGAATAGGAACAGTCTGTTTCCACTAT
        TTAATAATGCTACTTTTGAAAATTGTTAACTTTTTATTAAAAAATAATACTTGCAATTGACTTATGTATC
        AAGCAATCGATGGATTTATAGGGTTTAAGGAAAAGAAAAATGTTTGTCTGTCCAAGAATACCAGTTCTTC
        AGTCTTCCCCTTCAGAATCAATCAATGTTACCAATTTCTTATATATCCTAGCAAATACAAATATATTTAT
        ATTTGCATGTGTATACCTTTTAGATTTTTAAAAAATGCAATTGCAAATGCACCATGTGAATTGTTCTGCA
        ATGTACTAGCAATATATTAGAGACATCTTATCCATACATAAACCTAGTTCATTATTTTTAATCGATAAGT
        AAAACTTTGAGGAGGAGCAGATGAATTGCCTCACATTAATTACTCCGCTACTGATGAAAAATAGGTCTTT
        AATTATCAAAAACAATTCAGCAAGAAAAATTTGTAAACAAATGTATGTCTTTTCATTTATGACTGGACAC
        GTGGACACACACACACACACACACACACACACAGTCAAACCACCTACCAGAAAAGCTGAACTATTCTTCT
        CTCCTATCACCAGTTGCAAGAGTGTCAGCTTCCCACACCCTCATCAGTCCTTTTTGTTTTTTCTACTACA
        TTCAGTTTTCTACTACATTCAGTTTTACAGTCTAATATGTGAAAATGATGTCCTGATGTTTGAATTCATG
        ACACTTTAGTTATAAATGAGTTTGAACATCCAGTCCATTAGATTTCTAAACTTTCTTAATTATCTTTATA
        TACTAAGAAATTTGGCTTTTGTTAAATTTGGAGGTGTTATATGTTGCCTAGAAAGATGCTATTCATGTCT
        ATTAAATGGTTATAACTGTGCCTATGATCTGTTATGTCTTGATTCACATGTTGATGTAATGTGAGTTACA
        GAATTAATATCTACATTCATTTCTGATTATAAACTGCTGTATTTGTTGAAAATTTGGAAATTTTGAAATT
        GTAAAGAAGTAAAAAAATTGTAAAGAAGTTAAAAGAGACAAAATATTTTTGATCTATTGTTCTTCCTCAG
        TTTTCTTATTTGAATAAAAATGTATAGCATACTTATAAATTTTCTATTATACTATTAGTATTTTCCCATT
        TACTATTTTCAAAAACTGTATTTCCAATGACTGTATAAATTTTATAGAATGGATACTGTTTAAATTACTT
        AGCCAAATTGTTTTTGCATAAATAAGTGCATTTACATTTTATAGACAAGGATGGCTAGTATAACCTTTCT
        TATACATAAATCATTCAGCATAAAATTCCTGGAGATGTACTTTTTTCTGTCTGCTTCATGTGTTATCAAT
        TTTTGAATACTTGCCAAGTCCTAAAAATGAAATATTATATATAAATATTTAATTTTTATTTATGTCTGTG
        AGTAATGGGGAAGTCGAACTTCAAATACATGCTTAATGTATATTTAACTTTTCTACAAATTGTCTATGTC
        TCTCTTTCTCTTTTATTTTGGAGAGGTAGTTTTCATTTCTTTTGATTTAGAGATTTTCATTTTTGTGTTC
        TCTTATAGGTTTTGTTTTGAAATTTAGCTATTTAGTCTCTCTGGGCTTTATATTATGTGTTTTCAAGTGA
        GATAGCACCTGATGGCTTGTGAAGCAACTTTTTACCAAGCCAAGCTATCAGTGGACTGGTATCCATAGAT
        ATATTTTAAGTTGATGCTAGCTGATTATATATCTGGTATGTTTTAGAAAGAACTCCACACATGGGATAAT
        GTTTTGGCTAGATGGCTCCCCTACTTAGAAACATACAATTGCTAGTCATATTTCTAATTTTAGGATTTCG
        AGATACTGGTGATGAAGATCACATGTCCTAACAACATAATAGTTCCAGACTGAAGTTCTTTGAAAAAAAT
        GACTGTTGTCACTTTAGAAAAAAAAAATTATGAATTATTCCCAATTGCCATCATTCTACTGCTAAAACCA
        AATTCTTGGAATTATCTATGATTTTTCTATATCCTATGACACTCATATCTATCAGGAAGTCTATTACATC
        TGCCTGCAAATTATATCCAGAATGCAATTATTCTCGCCACCTCCATTGCTGCCACTCTGATTCTAGTCAC
        CATCATCTCTCACCTGTGTTATTGCCATAGCTTCCTCATGAGATCTGTCCTTCTGCTCTTCCCTGCCACC
        ATCTTGTGAAGACACATAGTGCATGATCCGCTTACACTGGAAGTCAGATCATGTACTTTTGCTCAAAACT
        CTGCTATGGCCCCCTCTATACTCAGAGCGGTAACAAGAGTCCATACAGTGGCTCACCTGGCCCTGCAGGA
        TCTGGCCCTTATGACCTCTCTCACCTCATCTCCTACTATTATAGTCCTTGTTCACTCCACTACAGCCACA
        CAAGCCCCAGTGCTCTTCCCCAAACATATCAGACTTACTCAACCCATAGAGCTTTGTTTGTTTCCTCTGC
        CTAGAATGTACTTGCCTCAGATACTGGTGTGACTAATTCCTTTACCTCCTTCAAGCTGTTTAATCATCAC
        CTTGTTACACAGGCTTGTGCAACTCCTGTTTATGAATCTTCTATTACCCTTAAATCTATTCTCCCTTCTT
        TCTGCAAACCATTTGTCACCTTTTCATCTACAAAATAATGTACTTTTTTATTAAGGTAAAATATACATTT
        AAAAATTACCATCCTTACCATGTTTTTACCATATTTTTATGTATACCTGATGGCTGTTTGTATGTCTTCT
        GTTGAGAAATGTCTATTCAAATCTTTTGCCTGTTTTAAAATCAGATTATTTGTTTTTGTTTGCTATGGAG
        TTTTTTGAGCTCCTTATATTAATATACTTTTTGTTGTTAATTCCTCGTCAGATGGATAGCTTGCAAATAT
        TTTCTCCTACTCTGTGGGCTACATCTTCACTTTGTTGATTATTTCCTTTGCTGTGCACAAGCTTTTTAGT
        TTGATGTAATCCTAATTGCCTATTTTTGCTTTGGTTGCCCGTGCTTTTGAGGTCTTACCCAAGAAATCTT
        TGCCAAGACCAACGTCCTGAAGTGTTTCCCTAATGTTTTTTTCAGGTAGTTCCATAGTTTCAGGTCTTAG
        ATTTAAGTCTGTAAAACCATACAGTCTAGCAGGGAGTGCATTTACTTTTTATTATCTGTCTCCCTCTGCT
        AGAAAGTCAGCTCCATGTGATTTTTGTCTGTTTAGTTCACAGATGTACCTCAAGGGCCCAGGATAGTGCC
        TGTGCCATAGTAGGGGCCCAAAACTTTGATGACTGTGTGACTATAGCCTAATTTAAGAATGGAGGGGATA
        ATTTAAAAGCAGTAGGAAGGAATGTAAGTGAGAAACAATTTTGAAGAATAATTGACAGAACAAGGCGATT
        CAAAGACAAAGGAGAAGAAGAGAGCCAAGATGACATATTTCAAGTATGGATAATGCTGGAGGAAAAAAAT
        TAAGATATAAATCTTTGTAGATGTGAGGAACGAAGAAGCAAGGTTAGAGTCTGTCTTGCACAAAAGAAGT
        GGAAGGTCTAGACTTGAAACTTATAGAAAATTCCACGAAGTACAAAGTAAAATCGAGCCAGTAAAATAAC
        AAAGATAGAATAAATGACTCTAGAGGAGTGAAGGTAGAATAAATAATTGGTGAAGCTGGACTAGAGCCAA
        CATTTCCCAGAGGATAAAATATAAACCAAATTATTGTGAGCCTAATATATACATACATACATACATCTAT
        ATATGTTTTATATATATTATCACATTAAGTTCAAATAAGGTTGTTTAGAAAATTACTTGCTCTTCTGCAC
        ATATACCAGGCTTCCTCCTCCATAGAGCCTTATCTCTAGCTGCTTCCTCTGCCTAGAATACACTTATCTA
        GGTACTCCTTGGGCAATTGTCTTGAGAAAGATGATCATGCCGTTTACTGCTTGATAAATGAACATACAAT
        GCAGCACACTAGTTTCCCTTTAGATTTATATCCTCACCCCTCAAATGAGTAGTCACACTGCTTGGAAATC
        CTACTGCATTTCTCTTGTAAATGAACCTTCCTTCTTTTTTTTTTTTTTTTGAGACAGAGTCTTTCTCTGT
        CACCAGGCTGGACTGCAGTGGCCCAATCTCGGCTCATTGCAACCGCCAACTCCCTGGTTCAAGTGATTCT
        CCTGCCTCAGCCTCCCGAGTAGCTGGGATCACAGGCATGTGCCACCACATCCAGCTAATTTTTATATTTT
        TAGTAGAGACAGGTTTTCACCAGGTTGGCCAGGATGGTCTCGATCTCCTGACCCTGTGATCCACCCTCCT
        CGGCTTCCCAAAGTGCTGGGATTACAGGTTTGTACCACCACACCCAGCCATCTTCCCTCTTTTTTAGACA
        ACTATTTTGTCCTGACCTTTATTTGTCTTTTATTTTCCTGCTCCTCTCCTCTACATGGCTCTCCCCCTCA
        GTTTATCCCATGCCCCATTTATTTAAACAATTCAAATAGGAAGTTTTCACTCATTTCCTCTGTCCCCTTT
        GCCATAAATGGAGAAACGTGTCTTCTCCATCTAAAGATCAGTCTGCTCTGTGTGAATTTGTGACTATGCC
        CTTCTGTCATCTCATCACCCTATTCTATATTAATCTCTCCTTTTCTGCTTTTTTTTTTTTTTTTTTGAGA
        TGGAGTCTTGCTCTTGTTGCCCAGGCTGGAATGCAGTGGCACAATCTTGGCTTACTGCAACCTTCGCCTC
        CCAGGTTCAAGTGATTCTCCTGCCTCAGCATCCTGAGTAGCTGGGACTACAGGTGCTCGCCACCATGCCC
        AGCTAATTTTTGTATTTTTTAGTAGAGACAGGGTTTCACCATGGCCAGGCTGGTCTCGAACTCCTGAACT
        CAGGTGATCTGCCCGCCTCGATCTCCCAAAGTGCTGGGATTACATGTGTGAGCCACTGCGCCCAGACTGC
        TTGTCTCTTTTCTCATTGCTTGCAAGCACCATTTGGTATTTCTCGTTCTTCAAAACAAACCTGAAAGCTT
        TCCCTTAACCTTACATTGCTCTCTAACAAGTTATTTATTTCTCTGCTTTTCTTTGGATCTAAACTTCTTA
        AGAGTTTCATCTACAGGTCCTGCATTCACTTCTCTCTCATTCACATTTTGACCAACTGCAATTTGGTTTC
        TTTTTTCATACCACTCGGAAGCTGCTCTCCTCAGTATGAAGTTACCTTCATACTACTAAAAGCATGGACA
        TTTTCCTGCCTTCATCATTTTTTTTTAACCTCTCAGCAGTATTTGACTACAAAATGACCACTCTGTCCTT
        TAAGAAACAGTCTCCTCTCCTGCTTAATGTAGTCACATCTGATACAACTTTCCCCATAACCTTTTATGCA
        TTTTCTGTTTTCATGCATATCAGCCCAACTTGCAATTGTCAGTATCTCCAGTCTTTCAACAACTGCTTGT
        GAAATACCCCTGTACAGGGCAATCCAGAAATGCCAGAAAATTATCAGCTGTCTCTGGATCATCTGTCAAC
        TATGGGGGAAGCTGGATAAATAGTCCAGGTCCTTTGAGCCTCATGTAGAATAACTTTGAGGCTTGGTAAT
        ATTTTTTTTTTCCTGTGGTAATTCCCTTATTTGCAGTTCAAGGCTATTATGGGAAGAAAACATAAATGGA
        TGTTAGTTCTTCAAGGTTTTTACTGTAACTGTGCACCCTTTCATTCTTCAAGGTTTTTCTGTAACACTGC
        ACCTTCAGGACCTGATGCCCAATTAAACATTTTTTTAAGTTTTTTGGTTTTTTTTTAATAAAAACTAAAT
        GCTATTTTTTCTTCTACTTTTAGTTGATGTGTAATAATTGTTCATATTTAGAAGATGCAGAGTGATATTT
        TGATACATGTATACAATGTGTAATGATCAAATCAGGGTAATTAGCATATCTATCACCTCAAACATTTGTC
        ATTTTTTTATATTGGGAACATTCAGAATCGTCTCTTCTAGCTATTTGAAAATATACAGTAAATGATTGTT
        AACTACCGTCACCCTACAGTGCTATAGAACAGTGGACCCCTTTTGGCACCAGGGACCAGTTTTGTGGAAG
        ACAGTTTTTTCGACGAGGTGAAGGTGGTGGTGGGGATGGTTTCAGGATGAAACTGTTCCACCTCAGGTCA
        TCAGGCATTAGAGTCTCACAAGGAACACACATCCTAGATCCCTCACATGCACAGTTCACAATAGGGTTCA
        TGCTCCTATGAGACTCTAATGCCTTGGCTGATCTGACAAGAGATGGAGCTCAGGTGGTGATGCTTGCACA
        CCTGCTGTTCACCTTTTGCTGTGCAGCCTGGTTCCTAACAGGCCATGGACCAGTACCCATTGGCTGCCCA
        GGGGTTGGGGACCCCTGCTATAGGATGCTGGAACTTTTTCCTCCTATCTAGGTGTAATTTTCTATCTGTT
        AACCAACCTCTCTCTATCCTCCTTTCCCTTCCCAGCCTCTAGTAATCATTATTCTACAGTCTACTTCTAT
        GAACTCAACTTTTTTAGCTCCTGCTTATGAATGAAAACATGTGGTATTTATCTTTTTGTGTCTATTTCAC
        ATAACGGAATGTAACATGTCCCCCAGGCTCATCCATGAGTCTGAGGCTTATTTGTAGCCTGGCTGCTGGG
        CTTCCCTGTGGGATTGTCCTCTGAGCAAACAGAACACAGCCATCCTGCTGGCCAGCAGTTGATAGATGAT
        CTCATGATAATAACAGGTTATAACTCACCTTTTCTTGGATTTCTTGCTTTCCTGATTTCTACATTTCTCC
        ACTGATTTTTTTTAAGGAGGAATTGTCTCTCAACTAAACTATTATATTCAAATCTTTGCTGGAGCTCTGC
        TCTGCTGGGGGTCTGCTTTAAGACTCTAGAGTCTTATTCTCCTGTTTTGATCTGACTTATCTTATTGGTC
        CTTTTAAGTCGTTTCCTCTTATCTGATCTCTTATCTCTTAATATTGAAACTCACTAGAATTTAATTCTAG
        TCCTCTTTTTTTCTCATATTATTCCAACCCACCATGGTTTACCAATTTCTGTACTTTAAATGCTATCCAT
        AAGCAATCACATTTATTGATTTGCATATGTCGAACCAACCTTGCATTCCAAGGATAAAGGCTACTTGATC
        GTAGTGGATAAGCTTTTTGATGTGCTGCTGGATTCAGTTTGCTACTATTTTGTTCAGGATTTTTGCACTG
        ATGTTCATCAAGGATACTGGCCTGAAATTTTTTTTTTCTTGTGTCTCTGCTAGGTTTTGGTCTCAGGATG
        ATGCTGGCCTCATAGAATAAGTTAAAGCGGAGTCCTGCCTTCTCAATTTTGGGTGAATAGTTTCAGTAGG
        AATGATACCAGCTCTTCTTTGTATATCTGGTAGAATTCAGCTGTGAATCCATCTGGTCCTGGGCTTTTCA
        TTTTCATCCTTTCTTTCTAGGTTTCGTATCAGTCTCAGTATGCTCTCTCTCTCTCCGTCCCTCTCTTTTT
        CTACATTTCTCCTTTTCTCCATACAACTTCTTTGATGGCACATAGCACAATTTTAATATACACTTTTTGT
        TCTCCTGTTTGTCTCTTACAATGGCTTTTTGTATTTGACATCATATTAGTCTAGATGTCAGTCAGTGTAA
        ATTTTTGAATGAATGAAAAGTTGTTATGTTGATGCCAGAGTTAAAAATTTGACCTATATTTTATTCTCTA
        CAGGTAGCTTTGAACCCCAAAAATGTTGGAAGAATAATGTAGGACATTGCAGAAGACGATGTTTAGATAC
        TGAAAGGTACATACTTCTTTGTAGGAACAAGCTATCATGCTGCATTTCTATAATATCACATGAATATACT
        CGACGACCAGCATTTCCTGTGATTCACCTAGAGGATATAACATTGGATTATAGTGATGTGGACTCTTTTA
        CTGGTTCCCCAGTATCTATGTTGAATGATCTGATAACATTTGACACAACTAAATTTGGAGAAACCATGAC
        ACCTGAGACCAATACTCCTGAGACTACTATGCCACCATCTGAGGCCACTACTCCCGAGACTACTATGCCA
        CCATCTGAGACTGCTACTTCCGAGACTATGCCACCACCTTCTCAGACAGCTCTTACTCATAATTAATTAA
        CATTTACTTCTGGTATGGAACAACTAGAAATACTGCTGGAAATAATATCCAAAGAGCTGATTCTACCAAT
        CCAATTTCACCAGGAAAATTCCATCAGGGATTGGATGACCATGGGGATGGACATAATTGCTACTACCAAC
        ACAACAGCCAAG"""
        seq = seq.replace("\n", "")
        self.gene = Gene(seq, chr, start, stop, elements)

    # def tearDown(self):
    #     self.widget.dispose()
    #     self.widget = None

if __name__ == '__main__':
    unittest.main()
