# This file created by conda-build 3.18.9
# meta.yaml template originally from:
# /opt/recipe, last modified Thu Sep  5 19:30:41 2019
# ------------------------------------------------

package:
    name: samtools
    version: '1.9'
source:
    sha256: 083f688d7070082411c72c27372104ed472ed7a620591d06f928e653ebc23482
    url: https://github.com/samtools/samtools/releases/download/1.9/samtools-1.9.tar.bz2
build:
    number: '12'
    string: h10a08f8_12
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_8
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_8
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
    host:
        - _libgcc_mutex 0.1 main
        - bzip2 1.0.8 h516909a_0
        - ca-certificates 2019.6.16 hecc5488_0
        - curl 7.65.3 hf8cf82a_0
        - htslib 1.9 ha228f0b_7
        - krb5 1.16.3 h05b26f9_1001
        - libcurl 7.65.3 hda55be3_0
        - libdeflate 1.0 h14c3975_1
        - libedit 3.1.20170329 hf8c457e_1001
        - libgcc-ng 9.1.0 hdf63c60_0
        - libssh2 1.8.2 h22169c7_2
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1c h516909a_0
        - tk 8.6.9 hed695b0_1002
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h516909a_1005
    run:
        - htslib >=1.9,<1.10.0a0
        - htslib >=1.9,<1.10.0a0
        - libgcc-ng >=7.3.0
        - ncurses >=6.1,<6.2.0a0
        - zlib >=1.2.11,<1.3.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - samtools --help
        - samtools view 'https://example.com' 2>&1 | grep 'truncated file.' -q
about:
    home: https://github.com/samtools/samtools
    license: MIT
    summary: Tools for dealing with SAM, BAM and CRAM files
extra:
    copy_test_source_files: true
    final: true
    identifiers:
        - biotools:samtools
