# This file created by conda-build 3.15.1
# meta.yaml template originally from:
# /opt/recipe, last modified Mon Mar 25 00:16:35 2019
# ------------------------------------------------

package:
    name: htslib
    version: '1.9'
source:
    sha256: e04b877057e8b3b8425d957f057b42f0e8509173621d3eccaedd0da607d9929a
    url: https://github.com/samtools/htslib/releases/download/1.9/htslib-1.9.tar.bz2
build:
    number: '7'
    run_exports:
        - htslib >=1.9,<1.10.0a0
    string: ha228f0b_7
requirements:
    build:
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_6
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_6
        - libgcc-ng 8.2.0 hdf63c60_1
        - libstdcxx-ng 8.2.0 hdf63c60_1
    host:
        - bzip2 1.0.6 h14c3975_1002
        - ca-certificates 2019.3.9 hecc5488_0
        - curl 7.64.0 h646f8bb_2
        - krb5 1.16.3 h05b26f9_1001
        - libcurl 7.64.0 h541490c_2
        - libdeflate 1.0 h14c3975_1
        - libedit 3.1.20170329 hf8c457e_1001
        - libgcc-ng 8.2.0 hdf63c60_1
        - libssh2 1.8.1 h22169c7_0
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1b h14c3975_1
        - tk 8.6.9 h84994c4_1000
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h14c3975_1004
    run:
        - bzip2 >=1.0.6,<2.0a0
        - bzip2 >=1.0.6,<2.0a0
        - curl >=7.64.0,<8.0a0
        - libdeflate >=1.0,<1.1.0a0
        - libgcc-ng >=7.3.0
        - xz >=5.2.4,<5.3.0a0
        - xz >=5.2.4,<5.3.0a0
        - zlib >=1.2.11,<1.3.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - ldd $PREFIX/bin/bgzip | grep deflate
about:
    home: https://github.com/samtools/htslib
    license: MIT
    summary: C library for high-throughput sequencing data formats.
extra:
    copy_test_source_files: true
    final: true
    identifiers:
        - biotools:HTSlib
