# This file created by conda-build 3.18.9
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/setuptools-41.4.0-python_3.7-on-linux_64, last modified Mon Oct  7 14:41:39 2019
# ------------------------------------------------

package:
    name: setuptools
    version: 41.4.0
source:
    patches:
        - 0001-Remove-exact-pinning-on-certifi-and-wincertstore.patch
        - 0002-disable-downloads-inside-conda-build.patch
    sha256: 7eae782ccf36b790c21bde7d86a4f303a441cd77036b25c559a602cf5186ce4d
    url: https://pypi.io/packages/source/s/setuptools/setuptools-41.4.0.zip
build:
    entry_points:
        - easy_install = setuptools.command.easy_install:main
    number: '0'
    string: py37_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2019.8.28 0
        - certifi 2019.9.11 py37_0
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 he6710b0_1
        - openssl 1.1.1d h7b6447c_2
        - python 3.7.4 h265db76_1
        - readline 7.0 h7b6447c_5
        - sqlite 3.30.0 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 h7b6447c_3
    run:
        - certifi >=2016.09
        - python >=3.7,<3.8.0a0
test:
    commands:
        - easy_install --help
    imports:
        - easy_install
        - pkg_resources
        - setuptools
about:
    description: 'Setuptools is a fully-featured, actively-maintained, and stable
        library

        designed to facilitate packaging Python projects.

        '
    dev_url: https://github.com/pypa/setuptools
    doc_source_url: https://github.com/pypa/setuptools/tree/master/docs
    doc_url: http://pythonhosted.org/setuptools/
    home: https://github.com/pypa/setuptools
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: Download, build, install, upgrade, and uninstall Python packages
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - mingwandroid
        - msarahan
        - nicoddemus
        - ocefpaf
