# This file created by conda-build 3.15.1
# meta.yaml template originally from:
# /opt/recipe, last modified Sat Feb  2 11:16:42 2019
# ------------------------------------------------

package:
    name: libdeflate
    version: '1.0'
source:
    sha256: 6477a42d59b8c3fedda9d09b25e7ddfb71524c0029553c2a030e9d6887618a59
    url: https://github.com/ebiggers/libdeflate/archive/v1.0.tar.gz
build:
    number: '1'
    string: h14c3975_1
requirements:
    build:
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_6
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_6
        - libgcc-ng 7.3.0 hdf63c60_0
        - libstdcxx-ng 7.3.0 hdf63c60_0
    host:
        - libgcc-ng 7.3.0 hdf63c60_0
    run:
        - libgcc-ng >=7.3.0
test:
    commands:
        - echo "hey"
about:
    home: https://github.com/ebiggers/libdeflate
    license: MIT
    summary: libdeflate is a library for fast, whole-buffer DEFLATE-based compression
        and decompression.
extra:
    copy_test_source_files: true
    final: true
