# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# /opt/recipe, last modified Mon May 13 18:35:30 2019
# ------------------------------------------------

package:
    name: bcftools
    version: '1.9'
source:
    sha256: 6f36d0e6f16ec4acf88649fb1565d443acf0ba40f25a9afd87f14d14d13070c8
    url: https://github.com/samtools/bcftools/releases/download/1.9/bcftools-1.9.tar.bz2
build:
    number: '4'
    string: ha228f0b_4
requirements:
    build:
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_7
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_7
        - libgcc-ng 8.2.0 hdf63c60_1
        - libstdcxx-ng 8.2.0 hdf63c60_1
    host:
        - bzip2 1.0.6 h14c3975_1002
        - ca-certificates 2019.3.9 hecc5488_0
        - curl 7.64.1 hf8cf82a_0
        - krb5 1.16.3 h05b26f9_1001
        - libcurl 7.64.1 hda55be3_0
        - libdeflate 1.0 h14c3975_1
        - libedit 3.1.20170329 hf8c457e_1001
        - libgcc-ng 8.2.0 hdf63c60_1
        - libssh2 1.8.2 h22169c7_2
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1b h14c3975_1
        - tk 8.6.9 h84994c4_1001
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h14c3975_1004
    run:
        - bzip2 >=1.0.6,<2.0a0
        - bzip2 >=1.0.6,<2.0a0
        - curl >=7.64.1,<8.0a0
        - libdeflate >=1.0,<1.1.0a0
        - libgcc-ng >=7.3.0
        - xz >=5.2.4,<5.3.0a0
        - xz >=5.2.4,<5.3.0a0
        - zlib >=1.2.11,<1.3.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - bcftools -h
        - bcftools --version
        - bcftools plugin -lv
about:
    home: https://github.com/samtools/bcftools
    license: MIT
    summary: BCFtools is a set of utilities that manipulate variant calls in the Variant
        Call Format (VCF) and its binary counterpart BCF. All commands work transparently
        with both VCFs and BCFs, both uncompressed and BGZF-compressed.  Most commands
        accept VCF, bgzipped VCF and BCF with filetype detected automatically even
        when streaming from a pipe. Indexed VCF and BCF will work in all situations.
        Un-indexed VCF and BCF and streams will work in most, but not all situations.
extra:
    copy_test_source_files: true
    final: true
    identifiers:
        - biotools:bcftools
        - doi:10.1093/bioinformatics/btp352
